#ifndef SECRETS_H

#define WIFI_SSID "HERE GOES YOUR SSID"
#define WIFI_PASSWORD "HERE GOES YOUR PASSWORD"

#define ThingSpeak_API_KEY "HERE GOES YOUR THINGSPEAK API KEY"

#define WATCHDOG_KEY "HERE GOES THE WATCHDOG KEY"

#endif